overblog_graphql:
  definitions:
    mappings:
      types:
        - types: [yaml, graphql]
          dir: "%kernel.project_dir%/vendor/atoolo/graphql-search-bundle/src/Resources/schema/defaults"
          suffix: ~
