overblog_graphql:
  definitions:
    mappings:
      types:
        - types: [yaml, graphql]
          dir: "%atoolo_graphql_search.config_dir%/graphql/defaults"
          suffix: ~
        - types: [yaml, graphql]
          dir: "%kernel.project_dir%/config/graphql/types"
          suffix: ~
